window.productsData = [
  // Electronics
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    description: "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and exceptional sound quality. Perfect for music lovers and remote workers.",
    price: 249.99,
    category: "Electronics",
    brand: "SoundWave",
    tags: ["audio", "wireless", "noise-cancelling", "bluetooth", "headphones"],
    rating: 4.7,
    reviews: 1234,
    stock: 45,
    inStock: true,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
    relatedProducts: [2, 3, 7, 8],
    viewCount: 8920,
    purchaseCount: 2341
  },
  {
    id: 2,
    name: "4K Smart TV 55\"",
    description: "Crystal clear 4K display with HDR10+, built-in streaming apps, voice control, and smart home integration. Transform your living room experience.",
    price: 699.99,
    category: "Electronics",
    brand: "VisionPro",
    tags: ["tv", "4k", "smart", "streaming", "hdr"],
    rating: 4.5,
    reviews: 876,
    stock: 22,
    inStock: true,
    image: "img/products/smartTV.jpg",
    relatedProducts: [1, 3, 6, 10],
    viewCount: 12450,
    purchaseCount: 1890
  },
  {
    id: 3,
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with tactile blue switches, anti-ghosting technology, and programmable macro keys for the ultimate gaming experience.",
    price: 129.99,
    category: "Electronics",
    brand: "GameForce",
    tags: ["gaming", "keyboard", "rgb", "mechanical", "pc"],
    rating: 4.6,
    reviews: 2100,
    stock: 78,
    inStock: true,
    image: "img/products/keyboard.jpg",
    relatedProducts: [4, 5, 1, 2],
    viewCount: 9870,
    purchaseCount: 3210
  },
  {
    id: 4,
    name: "Wireless Gaming Mouse",
    description: "Ultra-precise wireless gaming mouse with 25,600 DPI sensor, 70-hour battery life, 11 programmable buttons, and RGB lighting.",
    price: 89.99,
    category: "Electronics",
    brand: "GameForce",
    tags: ["gaming", "mouse", "wireless", "rgb", "pc"],
    rating: 4.8,
    reviews: 1567,
    stock: 103,
    inStock: true,
    image: "img/products/mouse.jpg",
    relatedProducts: [3, 5, 1, 2],
    viewCount: 7650,
    purchaseCount: 2890
  },
  {
    id: 5,
    name: "Laptop Stand Adjustable",
    description: "Ergonomic aluminum laptop stand with 6 height adjustments, foldable design, and universal compatibility. Improve your posture while working.",
    price: 49.99,
    category: "Electronics",
    brand: "ErgoTech",
    tags: ["laptop", "stand", "ergonomic", "aluminum", "portable"],
    rating: 4.4,
    reviews: 893,
    stock: 250,
    inStock: true,
    image: "img/products/PC-Stand.jpg",
    relatedProducts: [3, 4, 6, 7],
    viewCount: 5430,
    purchaseCount: 1240
  },
  {
    id: 6,
    name: "Smartphone Fast Charger 65W",
    description: "GaN fast charger with 65W output, supports USB-C PD and QC 4.0. Charges most devices to 50% in just 20 minutes. Compact travel-friendly design.",
    price: 39.99,
    category: "Electronics",
    brand: "PowerUp",
    tags: ["charger", "fast-charging", "usb-c", "gan", "smartphone"],
    rating: 4.5,
    reviews: 3456,
    stock: 400,
    inStock: true,
    image: "img/products/charger.jpg",
    relatedProducts: [7, 8, 1, 3],
    viewCount: 15670,
    purchaseCount: 5430
  },
  {
    id: 7,
    name: "True Wireless Earbuds",
    description: "Premium TWS earbuds with active noise cancellation, 8-hour playtime (32 hours with case), IPX5 water resistance, and seamless device switching.",
    price: 159.99,
    category: "Electronics",
    brand: "SoundWave",
    tags: ["audio", "wireless", "earbuds", "anc", "bluetooth"],
    rating: 4.6,
    reviews: 2345,
    stock: 87,
    inStock: true,
    image: "img/products/earbuds.jpg",
    relatedProducts: [1, 6, 8, 3],
    viewCount: 11230,
    purchaseCount: 4120
  },
  {
    id: 8,
    name: "Portable Bluetooth Speaker",
    description: "360-degree surround sound portable speaker with 20-hour battery, IPX7 waterproof rating, and built-in microphone for hands-free calls.",
    price: 79.99,
    category: "Electronics",
    brand: "SoundWave",
    tags: ["audio", "bluetooth", "portable", "waterproof", "speaker"],
    rating: 4.3,
    reviews: 1876,
    stock: 134,
    inStock: true,
    image: "img/products/speaker.jpg",
    relatedProducts: [1, 7, 6, 2],
    viewCount: 8900,
    purchaseCount: 2780
  },

  // Fashion
  {
    id: 9,
    name: "Classic Leather Jacket",
    description: "Genuine leather biker jacket with quilted lining, multiple pockets, and YKK zippers. A timeless wardrobe staple that gets better with age.",
    price: 299.99,
    category: "Fashion",
    brand: "UrbanEdge",
    tags: ["leather", "jacket", "biker", "men", "outerwear"],
    rating: 4.7,
    reviews: 567,
    stock: 34,
    inStock: true,
    image: "img/products/jacket.jpg",
    relatedProducts: [10, 11, 12, 13],
    viewCount: 6780,
    purchaseCount: 890
  },
  {
    id: 10,
    name: "Women's Floral Midi Dress",
    description: "Elegant floral print midi dress with v-neck, flutter sleeves, and flowing silhouette. Perfect for summer occasions and casual outings.",
    price: 79.99,
    category: "Fashion",
    brand: "BloomStyle",
    tags: ["dress", "floral", "women", "summer", "midi"],
    rating: 4.5,
    reviews: 1234,
    stock: 89,
    inStock: true,
    image: "img/products/dress.jpg",
    relatedProducts: [9, 11, 12, 13],
    viewCount: 9870,
    purchaseCount: 2340
  },
  {
    id: 11,
    name: "Slim Fit Chino Pants",
    description: "Classic slim-fit chino pants in stretch cotton blend. Available in multiple colors. Versatile enough for both office and weekend wear.",
    price: 59.99,
    category: "Fashion",
    brand: "UrbanEdge",
    tags: ["pants", "chino", "men", "slim-fit", "casual"],
    rating: 4.3,
    reviews: 789,
    stock: 145,
    inStock: true,
    image: "img/products/pants.jpg",
    relatedProducts: [9, 12, 13, 10],
    viewCount: 5430,
    purchaseCount: 1670
  },
  {
    id: 12,
    name: "Casual Sneakers",
    description: "Lightweight canvas sneakers with memory foam insoles, vulcanized rubber soles, and breathable upper. Classic style meets everyday comfort.",
    price: 69.99,
    category: "Fashion",
    brand: "StepStyle",
    tags: ["shoes", "sneakers", "casual", "canvas", "comfortable"],
    rating: 4.4,
    reviews: 2100,
    stock: 210,
    inStock: true,
    image: "img/products/sneakers.jpg",
    relatedProducts: [9, 10, 11, 13],
    viewCount: 11230,
    purchaseCount: 3450
  },
  {
    id: 13,
    name: "Wool Blend Scarf",
    description: "Luxurious wool blend scarf in classic plaid pattern. Extra-long 72\" length for multiple styling options. Soft, warm, and wrinkle-resistant.",
    price: 34.99,
    category: "Fashion",
    brand: "WarmKnit",
    tags: ["scarf", "wool", "winter", "plaid", "accessories"],
    rating: 4.6,
    reviews: 456,
    stock: 178,
    inStock: true,
    image: "img/products/scarf.jpg",
    relatedProducts: [9, 10, 11, 12],
    viewCount: 4560,
    purchaseCount: 1230
  },

  // Books
  {
    id: 14,
    name: "The Art of Machine Learning",
    description: "Comprehensive guide to machine learning algorithms, neural networks, and practical applications. Includes 50+ coding exercises and real-world case studies.",
    price: 49.99,
    category: "Books",
    brand: "TechPress",
    tags: ["machine-learning", "ai", "programming", "data-science", "technical"],
    rating: 4.8,
    reviews: 2345,
    stock: 567,
    inStock: true,
    image: "img/products/ArtML.jpg",
    relatedProducts: [15, 16, 17, 18],
    viewCount: 13450,
    purchaseCount: 4560
  },
  {
    id: 15,
    name: "Clean Code: A Developer's Guide",
    description: "Learn the principles of writing maintainable, readable, and efficient code. Essential reading for every software developer who wants to level up their craft.",
    price: 39.99,
    category: "Books",
    brand: "CodePress",
    tags: ["programming", "software", "best-practices", "developer", "technical"],
    rating: 4.9,
    reviews: 5678,
    stock: 890,
    inStock: true,
    image: "img/products/CleanCode.jpg",
    relatedProducts: [14, 16, 17, 18],
    viewCount: 23450,
    purchaseCount: 8900
  },
  {
    id: 16,
    name: "The Psychology of Money",
    description: "Timeless lessons on wealth, greed, and happiness. Explores how people think about money and how to make better financial decisions for long-term wealth.",
    price: 24.99,
    category: "Books",
    brand: "FinanceRead",
    tags: ["finance", "psychology", "money", "investing", "personal-development"],
    rating: 4.7,
    reviews: 7890,
    stock: 1200,
    inStock: true,
    image: "img/products/moneyBook.jpg",
    relatedProducts: [14, 15, 17, 18],
    viewCount: 34560,
    purchaseCount: 12300
  },
  {
    id: 17,
    name: "Atomic Habits",
    description: "Discover the science behind habit formation and learn practical strategies to build good habits, break bad ones, and master the tiny behaviors that lead to extraordinary results.",
    price: 27.99,
    category: "Books",
    brand: "GrowthRead",
    tags: ["habits", "self-help", "productivity", "personal-development", "psychology"],
    rating: 4.8,
    reviews: 12345,
    stock: 2340,
    inStock: true,
    image: "img/products/atomicHabits.jpg",
    relatedProducts: [14, 15, 16, 18],
    viewCount: 45670,
    purchaseCount: 18900
  },
  {
    id: 18,
    name: "JavaScript: The Good Parts",
    description: "Douglas Crockford's essential guide to the best JavaScript features. Learn to write more reliable, readable, and maintainable code by focusing on JavaScript's most elegant features.",
    price: 34.99,
    category: "Books",
    brand: "TechPress",
    tags: ["javascript", "programming", "web-development", "technical", "developer"],
    rating: 4.6,
    reviews: 4567,
    stock: 678,
    inStock: true,
    image: "img/products/jsGP.jpg",
    relatedProducts: [14, 15, 16, 17],
    viewCount: 19870,
    purchaseCount: 6780
  },

  // Home & Garden
  {
    id: 19,
    name: "Smart Indoor Herb Garden",
    description: "Self-watering indoor herb garden with LED grow lights and automated watering system. Grow fresh herbs year-round, no gardening experience required.",
    price: 89.99,
    category: "Home & Garden",
    brand: "GreenHome",
    tags: ["garden", "herbs", "smart", "indoor", "plants"],
    rating: 4.5,
    reviews: 1234,
    stock: 67,
    inStock: true,
    image: "img/products/herbgarden.jpg",
    relatedProducts: [20, 21, 22, 23],
    viewCount: 7890,
    purchaseCount: 2340
  },
  {
    id: 20,
    name: "Stainless Steel Cookware Set",
    description: "10-piece professional-grade stainless steel cookware set with tri-ply construction, ergonomic handles, and oven-safe up to 500°F. Dishwasher safe.",
    price: 249.99,
    category: "Home & Garden",
    brand: "ChefPro",
    tags: ["cookware", "kitchen", "stainless-steel", "cooking", "pots"],
    rating: 4.7,
    reviews: 2345,
    stock: 45,
    inStock: true,
    image: "img/products/cookware.jpg",
    relatedProducts: [19, 21, 22, 23],
    viewCount: 13450,
    purchaseCount: 3450
  },
  {
    id: 21,
    name: "Memory Foam Mattress Topper",
    description: "3-inch gel-infused memory foam mattress topper with cooling technology. Temperature-neutral design for all-night comfort. CertiPUR-US certified.",
    price: 119.99,
    category: "Home & Garden",
    brand: "DreamSleep",
    tags: ["mattress", "sleep", "foam", "bedroom", "comfort"],
    rating: 4.6,
    reviews: 3456,
    stock: 89,
    inStock: true,
    image: "img/products/mtrxtopper.jpg",
    relatedProducts: [19, 20, 22, 23],
    viewCount: 16780,
    purchaseCount: 5670
  },
  {
    id: 22,
    name: "Robot Vacuum Cleaner",
    description: "Smart robot vacuum with laser navigation, 3000Pa suction, auto-empty base, and app control. Compatible with Alexa and Google Home. Maps your home for efficient cleaning.",
    price: 449.99,
    category: "Home & Garden",
    brand: "CleanBot",
    tags: ["vacuum", "robot", "smart-home", "cleaning", "automated"],
    rating: 4.4,
    reviews: 1890,
    stock: 32,
    inStock: true,
    image: "img/products/vc.jpg",
    relatedProducts: [19, 20, 21, 23],
    viewCount: 23450,
    purchaseCount: 4560
  },
  {
    id: 23,
    name: "Aromatherapy Diffuser",
    description: "Ultrasonic essential oil diffuser with 7 LED colors, 400ml capacity, 4 timer settings, and auto-shutoff. Create a relaxing spa atmosphere at home.",
    price: 34.99,
    category: "Home & Garden",
    brand: "ZenHome",
    tags: ["aromatherapy", "diffuser", "essential-oils", "relaxation", "home-decor"],
    rating: 4.5,
    reviews: 4567,
    stock: 234,
    inStock: true,
    image: "img/products/diffuser.jpg",
    relatedProducts: [19, 20, 21, 22],
    viewCount: 12340,
    purchaseCount: 5670
  },

  // Sports
  {
    id: 24,
    name: "Adjustable Dumbbells Set",
    description: "Quick-select adjustable dumbbells replacing 15 sets of weights. 5-52.5 lbs per dumbbell with easy turn-dial selection. Space-saving home gym solution.",
    price: 349.99,
    category: "Sports",
    brand: "IronFit",
    tags: ["dumbbells", "fitness", "weights", "gym", "strength-training"],
    rating: 4.8,
    reviews: 3456,
    stock: 28,
    inStock: true,
    image: "img/products/dumbells.jpg",
    relatedProducts: [25, 26, 27, 28],
    viewCount: 18900,
    purchaseCount: 4560
  },
  {
    id: 25,
    name: "Yoga Mat Premium",
    description: "6mm thick non-slip yoga mat with alignment lines, carrying strap, and eco-friendly TPE material. Perfect for yoga, pilates, and floor exercises.",
    price: 49.99,
    category: "Sports",
    brand: "ZenFit",
    tags: ["yoga", "mat", "fitness", "pilates", "eco-friendly"],
    rating: 4.6,
    reviews: 5678,
    stock: 345,
    inStock: true,
    image: "img/products/yogamat.jpg",
    relatedProducts: [24, 26, 27, 28],
    viewCount: 23450,
    purchaseCount: 8900
  },
  {
    id: 26,
    name: "Smart Fitness Tracker",
    description: "Advanced fitness tracker with heart rate monitoring, GPS, sleep tracking, 50+ workout modes, and 7-day battery life. Water-resistant to 50 meters.",
    price: 199.99,
    category: "Sports",
    brand: "FitTech",
    tags: ["fitness", "tracker", "smartwatch", "health", "gps"],
    rating: 4.5,
    reviews: 4567,
    stock: 89,
    inStock: true,
    image: "img/products/smartwatch.jpg",
    relatedProducts: [24, 25, 27, 28],
    viewCount: 21340,
    purchaseCount: 6780
  },
  {
    id: 27,
    name: "Resistance Bands Set",
    description: "Set of 5 resistance bands (10-50 lbs) with handles, ankle straps, door anchor, and carry bag. Full-body workout system for strength and flexibility.",
    price: 29.99,
    category: "Sports",
    brand: "IronFit",
    tags: ["resistance", "bands", "fitness", "stretching", "workout"],
    rating: 4.4,
    reviews: 6789,
    stock: 567,
    inStock: true,
    image: "img/products/band.jpg",
    relatedProducts: [24, 25, 26, 28],
    viewCount: 15670,
    purchaseCount: 7890
  },
  {
    id: 28,
    name: "Running Shoes Pro",
    description: "High-performance running shoes with responsive foam cushioning, breathable mesh upper, reflective details, and heel drop technology for natural gait.",
    price: 139.99,
    category: "Sports",
    brand: "SpeedRun",
    tags: ["shoes", "running", "sports", "athletic", "comfortable"],
    rating: 4.7,
    reviews: 3456,
    stock: 123,
    inStock: true,
    image: "img/products/running-shoes.jpg",
    relatedProducts: [24, 25, 26, 27],
    viewCount: 19870,
    purchaseCount: 5670
  },
  {
    id: 29,
    name: "Protein Shaker Bottle",
    description: "BPA-free protein shaker with BlenderBall wire whisk, 28oz capacity, secure screw-on lid, and loop top for gym bag attachment. Dishwasher safe.",
    price: 14.99,
    category: "Sports",
    brand: "FitFuel",
    tags: ["shaker", "protein", "gym", "bottle", "fitness"],
    rating: 4.3,
    reviews: 8901,
    stock: 890,
    inStock: true,
    image: "img/products/bottle.jpg",
    relatedProducts: [24, 25, 26, 27],
    viewCount: 11230,
    purchaseCount: 9870
  },
  {
    id: 30,
    name: "Foam Roller for Recovery",
    description: "High-density EVA foam roller for muscle recovery, myofascial release, and deep tissue massage. 18-inch standard length, supports up to 500 lbs.",
    price: 24.99,
    category: "Sports",
    brand: "ZenFit",
    tags: ["foam-roller", "recovery", "massage", "fitness", "yoga"],
    rating: 4.5,
    reviews: 5678,
    stock: 456,
    inStock: true,
    image: "img/products/roller.jpg",
    relatedProducts: [25, 27, 26, 28],
    viewCount: 12340,
    purchaseCount: 6780
  },
  {
    id: 31,
    name: "Wireless Charging Pad",
    description: "15W fast wireless charging pad compatible with all Qi-enabled devices. Ultra-slim design with LED indicator, anti-slip surface, and temperature control.",
    price: 29.99,
    category: "Electronics",
    brand: "PowerUp",
    tags: ["charging", "wireless", "qi", "smartphone", "accessory"],
    rating: 4.4,
    reviews: 3456,
    stock: 234,
    inStock: true,
    image: "img/products/chargingpad.jpeg",
    relatedProducts: [6, 7, 1, 3],
    viewCount: 9870,
    purchaseCount: 4560
  },
  {
    id: 32,
    name: "Linen Throw Blanket",
    description: "Soft and breathable linen-cotton blend throw blanket. Perfect weight for all seasons. Machine washable, pre-washed for extra softness. 50\"x60\" size.",
    price: 44.99,
    category: "Home & Garden",
    brand: "CozyNest",
    tags: ["blanket", "linen", "bedroom", "cozy", "home-decor"],
    rating: 4.6,
    reviews: 2345,
    stock: 345,
    inStock: true,
    image: "img/products/blanket.jpg",
    relatedProducts: [21, 23, 20, 19],
    viewCount: 8900,
    purchaseCount: 3450
  }
];

window.getProductById = function(id) {
  return window.productsData.find(p => p.id === parseInt(id));
};

window.getProductsByCategory = function(category) {
  return window.productsData.filter(p => p.category === category);
};

window.getProductsByBrand = function(brand) {
  return window.productsData.filter(p => p.brand === brand);
};

window.searchProducts = function(query) {
  const q = query.toLowerCase();
  return window.productsData.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.tags.some(t => t.toLowerCase().includes(q))
  );
};

window.getCategories = function() {
  return [...new Set(window.productsData.map(p => p.category))];
};

window.getBrands = function() {
  return [...new Set(window.productsData.map(p => p.brand))];
};